#Application config
application:
  dist_name: blog-awesome
  application_home: /opt/blog-awesome/webapp
  jmx_port: 9010
  webapp_ram: 1024
  couchbase_host: 192.168.100.10
  buckets:
    - users
    - tags
    - comments
    - posts
