#Application config
application:
  dist_name: blog-awesome
  application_home: /opt/octopus/webapp
  jmx_port: 9010
  webapp_ram: 1024
  couchbase_host: 192.168.100.10
  default_bucket: octopus
  buckets:
    - octopus

#    TODO: switch from default bucket