# Couchbase configuration
couchbase:
  admin_user: admin
  admin_password: password
  cluster_ram_quota: 1500
  buckets:
    users:
      name: users
      password: bucket_password
      ram_quota: 256
      replica_number: 0
      enable_flush: 1
    tags:
      name: tags
      password: bucket_password
      ram_quota: 100
      replica_number: 0
      enable_flush: 1
    comments:
        name: comments
        password: bucket_password
        ram_quota: 256
        replica_number: 0
        enable_flush: 1
    posts:
        name: posts
        password: bucket_password
        ram_quota: 256
        replica_number: 0
        enable_flush: 1
  design_docs:
    - docname: blog_mr
      file: post_views.json
      buckets:
        - posts
    - docname: blog_mr
      file: comment_views.json
      buckets:
        - comments