# Couchbase configuration
admin_user: admin
admin_password: password

# ram quota for the cluster
cluster_ram_quota: 1024

buckets:
  octopus:
    name: octopus
    ram_quota: 512
    replica_number: 0
    enable_flush: 0
  test:
    name: test
    ram_quota: 256
    replica_number: 0
    enable_flush: 1

design_docs:
  - docname: octopus_mr
    file: mr_views.json
    buckets:
      - octopus
  - docname: octopus_mr
    file: mr_views.json
    buckets:
      - test