#SecureSocial keys
securesocial:
  facebook:
    id: 1473918236218553
    secret: a43e275d189b33dbc7dadf77a8ff1167
  twitter:
    id: vFH0fyZNjVmrxgPnV9oc7Xkeb
    secret: PCV4AauPaeLRgH0LOFN2J6e1Uc6GQs0LJJNAVviHRb8NmGe3TT