#SecureSocial keys
securesocial:
  facebook:
    id: 358078374356019
    secret: 3e9d392e6b2fe1881e002109fecc1ac5
  twitter:
    id: vFH0fyZNjVmrxgPnV9oc7Xkeb
    secret: PCV4AauPaeLRgH0LOFN2J6e1Uc6GQs0LJJNAVviHRb8NmGe3TT