- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration
  action: template src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Restarting nginx
  shell: service nginx restart