- name: Copy zip
  unarchive: src=../../../../target/universal/{{ application.dist_name }}.zip dest=/tmp/

- name: Kill Running Process
  action: shell sudo kill -9 $(cat {{ application.application_home }}/RUNNING_PID)
  ignore_errors: True

- name: Clear previous install
  action: file path={{ item }} state=absent
  with_items:
    - "{{ application.application_home }}"
    - play.*

- name: Moving to application HOME
  shell: mkdir -p {{ application.application_home }} && mv -f /tmp/{{ application.dist_name }}/* {{ application.application_home }}

- name: Create shell script for launching the App
  action: template src=launch.sh.j2 dest={{ application.application_home }}/bin/launch.sh mode=755

- name: Clear dev config
  action: file path={{ item }} state=absent
  with_items:
    - "{{ application.application_home }}/conf/securesocial.conf"
    - "{{ application.application_home }}/conf/couchbase.conf"
    - "{{ application.application_home }}/conf/application.conf"

- name: Copying SecureSocial configuration (overwrite)
  action: template src=securesocial.conf.j2 dest={{ application.application_home }}/conf/securesocial.conf

- name: Copying Couchbase configuration (overwrite)
  action: template src=couchbase.conf.j2 dest={{ application.application_home }}/conf/couchbase.conf

- name: Copying Application configuration (overwrite)
  action: template src=application.conf.j2 dest={{ application.application_home }}/conf/application.conf

- name: Launch Awesomeness
  action: shell nohup {{ application.application_home }}/bin/launch.sh
  async: 1000000
  poll: 0