- name: Copy zip
  unarchive: src=../../../target/universal/{{ dist_name }}.zip dest=/tmp/

- name: Kill Running Process
  action: shell sudo kill -9 $(cat {{ application_home }}/RUNNING_PID)
  ignore_errors: True

- name: Clear previous install
  action: file path={{ item }} state=absent
  with_items:
    - "{{ application_home }}"
    - play.*

- name: Make home dir
  shell: mkdir {{ application_home }}

- name: Moving to application HOME
  shell: mv -f /tmp/{{ dist_name }}/* {{ application_home }}

- name: Create shell script for launching the App
  action: template src=templates/startcutesy.sh.j2 dest={{ cutesy_home }}/bin/startcutesy.sh mode=750

- name: Copying SecureSocial configuration (overwrite)
  action: template src=templates/ssprod.conf.j2 dest={{ cutesy_home }}/conf/production/ssprod.conf

- name: Launch cutesy App
  action: shell nohup {{ cutesy_home }}/bin/startcutesy.sh
  async: 1000000
  poll: 0
