---

- hosts: all
  sudo: True
  vars_prompt:
      redeploy: Full redeploy or application only [full|app] ?
  vars_files:
    - prodconfig/flyingoctopus/couchbase.yml
  roles:
    - { role: common, when: "redeploy != 'app'" }
    - { role: oracle-java, when: "redeploy != 'app'" }
    - { role: couchbase, when: "redeploy != 'app'" }

- hosts: webapp
  sudo: True
  vars_prompt:
      redeploy: Redeploy Nginx and Datadog [yes|no] ?
  vars_files:
    - prodconfig/flyingoctopus/couchbase.yml
    - prodconfig/flyingoctopus/application.yml
    - prodconfig/flyingoctopus/datadog.yml
    - prodconfig/flyingoctopus/nginx.yml
    - prodconfig/flyingoctopus/securesocial.yml
  roles:
    - { role: nginx, when: "redeploy == 'yes'" }
    - role: appdeploy
    - { role: datadog, when: "redeploy == 'yes'" }