---

- hosts: all
  sudo: True
  vars_prompt:
      redeploy: Full redeploy or application only [full|app] ?
  vars_files:
    - secure-config/datastrophic/couchbase.yml
  roles:
    - { role: common, when: "redeploy != 'app'" }
    - { role: oracle-java, when: "redeploy != 'app'" }
    - { role: couchbase, when: "redeploy != 'app'" }


- hosts: webapp
  sudo: True
  vars_prompt:
      nginx_redeploy: Redeploy Nginx and Datadog [yes|no] ?
  vars_files:
    - secure-config/datastrophic/couchbase.yml
    - secure-config/datastrophic/application.yml
    - secure-config/datastrophic/datadog.yml
    - secure-config/datastrophic/nginx.yml
    - secure-config/datastrophic/securesocial.yml
  roles:
    - { role: nginx, when: "nginx_redeploy == 'yes'" }
    - role: appdeploy
    - { role: datadog, when: "nginx_redeploy == 'yes'" }